### ISSUE TITLE
Ability to collect application execution metrics

### ISSUE THREAD

**Issue by vijaynalawade** [TIBCOSoftware/flogo-lib#22] opened 2017-01-09 22:25 UTC
There should be pluggable way to collect application execution data for flow instances/activities/transitions.
This will help build app monitoring solutions for Flogo as well as WI.

**Comment by smanu** [comment] 2017-05-15 22:43
Duplicate of monitoring hooks.

**Closed by smanu** 2017-05-15 22:43 UTC
Labels: kind/enhancement, priority/P2, status/in-progress
